import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { Navbar } from '@/components/navigation/navbar';
import { ReactQueryProvider } from '@/providers/react-query/react-query-provider';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Swap Space',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color="var(--primary)"
          height={2}
          showSpinner={false}
          speed={800}
          easing="ease"
        />
        <NuqsAdapter>
          <ThemeProvider>
            <ReactQueryProvider>
              <Navbar />
              <div className="flex h-screen overflow-hidden ">
                <main
                  className="
                min-h-screen flex-1
                overflow-y-auto overflow-x-hidden
                py-24 
                
                flex flex-col
                
              "
                >
                  {children}
                </main>
              </div>
              <Toaster richColors />
            </ReactQueryProvider>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
