import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { Navbar } from '@/components/navigation/navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Beta App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Navbar />
          <div className="flex h-screen overflow-hidden border-collapse">
            <main
              className="
    min-h-screen flex-1
    overflow-y-auto overflow-x-hidden
    py-12 px-4      /* Default padding for mobile */
    sm:py-16 sm:px-6 /* Small devices (640px and up) */
    md:py-20 md:px-8 /* Medium devices (768px and up) */
    lg:py-24 lg:px-8 /* Large devices (1024px and up) */
    bg-secondary/20
    flex flex-col
  "
            >
              {children}
            </main>
          </div>
        </ThemeProvider>

        <Toaster richColors />
      </body>
    </html>
  );
}
